#przepływ pracy pokazujący jak tworzyć przepływy pracy w gałęziach

name: Develop in branch

on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
          echo "Przepływ pracy wyzwolony w odgałęzieniu '${{ github.ref }}'."
          echo "Przepływ pracy wyzwolony przez zdarzenie ${{ github.event_name }}."
          echo "Przepływ pracy wyzwolony przez aktora (użytkownika) ${{ github.actor }}."
      - uses: actions/checkout@v4.1.0
      - uses: devops-actions/actionlint@v0.1.2
