name: My first workflow
on: 
  push:
    branches: 
      - main
      - master

jobs: 
  first_job:
    name: Moje pierwsze zadanie
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world ${{github.actor}}"
          echo "Drugi rzad" 
      - name: Checkout
        uses: actions/checkout@v4.1
      - run: tree
  
  
  
  
