name: My first workflow
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  first_job:
    name: Moje pierwsze zadanie
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world ${{github.actor}}"
          echo "Drugi rzad is sekret: ${{secrets.TEST_SECRET}} "
          echo "Trzeci rząd is var: ${{vars.TEST_VARS}} "
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          echo "POZDROWIENIA dla ${{ vars.WHO_TO_GREET }} od ${{github.actor }}. "
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g') 
          echo "Moje zamaskowane hasło to: '$sec'."
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job
    steps:
      - run: |
          echo "Pozdrowienia dla ${{ vars.WHO_TO_GREET }} od ${{ github.actor }}."
          sec=$( echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "Moje zamaskowane hasło to: '$sec'."

  Show-Branches:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          echo "Aktualnie branche:"
          git branch -a
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]
    steps:
      - run: |
          echo 'Pozdrowienia dla ${{ vars.WHO_T_GREET }} od ${{ github.actor }}.'
          sec=$( echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "Moje zamaskowane hasło to: '$sec'."
