name: My first workflow
on: 
  push:
    branches: 
      - main
      - master
  workflow_dispatch:

jobs: 
  first_job:
    name: Moje pierwsze zadanie
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world ${{github.actor}}"
          echo "Drugi rzad isekret ${{secrets.TEST_SECRET}} "
          echo "Trzeci rzÄ…d isekret ${{vars.TEST_VAR}} "
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - run: tree
  
  
  
  

